context:
  version: "6.1.3"

package:
  name: junit5
  version: ${{ version }}

source:
  - git: https://github.com/junit-team/junit5
    tag: r${{ version }}
  - url: https://github.com/junit-team/junit-framework/archive/refs/tags/r${{ version }}.tar.gz
    sha256: f5a6c56c1575bf9f51313d89b3e2901a7be0dd3073ac14792838952c58853ae4
    target_directory: archive

build:
  number: 0
  noarch: generic

requirements:
  host:
    - git
    - maven
    - openjdk
    - sed
  run:
    - openjdk

tests:
  - script:
      - junit5 --help

about:
  license: EPL-2.0
  license_file:
    - LICENSE.md
    - build/reports/dependency-license/
  summary: The 5th major version of the programmer-friendly testing framework for Java and the JVM
  homepage: https://github.com/junit-team/junit5
  repository: https://github.com/junit-team/junit5

extra:
  recipe-maintainers:
    - danielnachun
