context:
  version: 5.10.3

package:
  name: junit5
  version: ${{ version }}

source:
  git: https://github.com/junit-team/junit5
  tag: r${{ version }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - git
    - maven
    - openjdk =17
    - sed
  run:
    - openjdk

tests:
  - script:
      - junit5 --help

about:
  license: EPL-2.0
  license_file:
    - LICENSE.md
    - build/reports/dependency-license/
  summary: The 5th major version of the programmer-friendly testing framework for Java and the JVM
  homepage: https://github.com/junit-team/junit5
  repository: https://github.com/junit-team/junit5

extra:
  recipe-maintainers:
    - danielnachun
